# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceb586603054d4801b457d0ee1896ca9306bce14467075c7f47e0af702e0258cea168632e1725cfc7768485c4994ada5f732a4be2125bfe5b9a835b3e406dab5

test:
  secret_key_base: 8cace6d2741d7344d77d7419a916d94ad09d1a4e8a33ecf485f930024a34bfecf91fd21a2bfec360c352ba0a7801fd81f8f3ac52465e09bc9671c575539cbd92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
